version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4392492n83rl"
s3_prefix = "test-stack"
region = "us-east-1"
profile = "super"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
